version: "3"

services:
  clojure-practice:
    build: .
    tty: true
    restart: always
    working_dir: "/workdir"
    volumes: 
      - ".:/workdir"
    ports:
      - 80:3000
  db:
    image: postgres:9.6
    tty: true
    restart: always
    volumes:
      - "./postgres/pgdata:/var/lib/postgresql/data/pgdata"
      - "./postgres/initdb:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_PASSWORD=password1234
      - POSTGRES_USER=TORA
      - POSTGRES_DB=database
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432